### ISSUE TITLE
JSON Parsing Error During 'mkc init' and 'mkc build' Commands

### ISSUE THREAD

**Issue by elecfreaks1** [microsoft/pxt-mkc#134]
**Issue Description:**
I'm unable to initialize a MakeCode development environment or build projects cloned from the repository. Despite testing multiple Node.js versions (including v22.14.0), all attempts fail with consistent JSON syntax errors during configuration parsing.

**Environment:**
OS: Windows (based on path C:\Coding\...)
Node.js: v22.14.0

<img width="855" alt="Image" src="https://github.com/user-attachments/assets/e9742131-0b30-4e07-b02a-57ef600bfc7d" />

**Comment by riknoll** [comment]
this is fixed, but i need to bump the package to release it... will do today!

**Comment by riknoll** [comment]
@elecfreaks1 this is fixed in makecode version 1.3.2! make sure to update your local install

**Comment by elecfreaks1** [comment]
After updating the MakeCode local version to 1.3.2, the same problem still occurs.

![Image](https://github.com/user-attachments/assets/aaf73ac2-fc5f-4662-afea-cb352ebc886a)

**Comment by elecfreaks1** [comment]
@riknoll

**Comment by riknoll** [comment]
whoops, looks like my parsing works for arcade but not micro:bit. fixing now...
